language: android
jdk: oraclejdk7
android:
  components:
  - build-tools-20.0.0
  - android-21
script:
  - ./gradlew clean build
before_install:
  - openssl aes-256-cbc -K $encrypted_ee19969afbf8_key -iv $encrypted_ee19969afbf8_iv -in deploy/secring.gpg.enc -out deploy/secring.gpg -d
